# Generated by Django 2.2.9 on 2019-12-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlappyClone', '0006_auto_20170410_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
